name: memories
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  uuid: ^4.3.3
  file_picker: ^8.0.0+1
  package_info_plus: ^5.0.1
  bitsdojo_window: ^0.1.6
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  # hive: ^4.0.0-dev.2
  # isar_flutter_libs: ^4.0.0-dev.13
  # path_provider: ^2.1.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  shared_preferences: ^2.2.3
  states_rebuilder: ^6.4.0
flutter:
  uses-material-design: true
